#!/usr/bin/env python3
import os
import requests
from datetime import datetime

now = datetime.now()
date_str = now.strftime('%Y-%m-%d')
is_pm = now.hour >= 12
file_suffix = "_PM" if is_pm else "_AM"
filename = "AI-Report_" + date_str + file_suffix + ".md"

system_prompt = """You are a professional AI industry analyst. Generate a comprehensive AI industry daily report based on the latest information.

The report must contain the following three sections in Markdown format:

## 1. Global AI/Tech/Investment Latest News
Search and organize the latest global AI, technology, and investment dynamics, including important model releases, funding events, product updates, and policy developments. Organize 5-10 key points, with important data in bold.

## 2. China AI Startup Data Analysis
Search for the latest dynamics of domestic AI startups, focusing on:
- Financing/investment actions (amount, round, investors)
- Sub-sectors (embodied AI/AI Agent/AI healthcare/AI chips, etc.)
- Emerging companies with development potential
Output structured analysis (tables + key points), covering at least 5 companies.

## 3. Shanghai AI-Related Events
Search for recent AI-related events in Shanghai on platforms like WeChat, Xiaohongshu, Toutiao, Luma, etc. (offline salons, forums, meetups, demo days, etc.). Organize as a table including: event name, time, location, registration channel/link. Focus on events available for registration in the next 7 days.

Format requirements:
- Use Chinese language
- Bold important data with **
- Each section has subtitles and key points
- Start the report with date and type (morning/evening report)
- End with "Generated by AI"
"""

user_prompt = "Please generate the AI industry daily report for " + date_str + ", focusing on the latest dynamics today and recently."

api_key = os.environ.get('NVIDIA_API_KEY')

if api_key:
    url = "https://integrate.api.nvidia.com/v1/chat/completions"
    headers = {
        "Authorization": "Bearer " + api_key,
        "Content-Type": "application/json"
    }
    payload = {
        "model": "nvidia/llama-3.1-nemotron-70b-instruct",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "max_tokens": 4000,
        "temperature": 0.7
    }
    
    response = requests.post(url, headers=headers, json=payload)
    if response.status_code == 200:
        result = response.json()
        content = result['choices'][0]['message']['content']
    else:
        content = "# AI Daily Report " + date_str + file_suffix + "\n\n[API Error: " + str(response.status_code) + "]\n"
else:
    content = "# AI Daily Report " + date_str + file_suffix + "\n\n[Please set NVIDIA_API_KEY in GitHub Secrets]\n"

with open(filename, 'w', encoding='utf-8') as f:
    f.write(content)

print("Report generated: " + filename)

github_output = os.environ.get('GITHUB_OUTPUT', '/tmp/github_output')
with open(github_output, 'a') as f:
    f.write("filename=" + filename + "\n")
